### ISSUE TITLE
Drop Event implementation and use a dependency?

### ISSUE THREAD

**Issue by cjsaylor** [zumba/symbiosis#22]
There are a couple of event implementations out there that are much better supported and use. Would it be in the best interest of this lib to drop our existing event implementation and use something like [Symfony's Event Dispatcher](https://github.com/symfony/EventDispatcher).

This way we can focus 100% on just the plugin architecture.

Thoughts?

**Comment by jrbasso** [comment]
:+1: 

Event Dispatcher from Symfony is very well known and supported. Building on top of it is a good idea. It reduces the library code to maintain, give more flexibility and features and easier to integrate too.
The only issue can be a dependency conflict, but I guess it is a small trade off.
